version: "3.8"
services:

  backend:
    build: ./services/backend
    env_file:
      - .env
    volumes:
      - ./services/backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "9000:9000"

  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=cenemat
      - POSTGRES_PASSWORD=cenemat
      - POSTGRES_DB=cenemat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
