version: "3.8"
services:

  backend:
    build: ./services/backend
    env_file:
      - .env
    volumes:
      - ./services/backend/src:/app
    ports:
      - "8000:80"
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "9000:9000"

  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  migrations:
    image: flyway/flyway:9.12
    command: -connectRetries=60 migrate
    depends_on:
      - db
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_GROUP=true
      - FLYWAY_CLEAN_DISABLED=${FLYWAY_CLEAN_DISABLED}
    volumes:
      - ./services/sql:/flyway/sql
