import os

# Database
DATABASE_URL = os.environ.get("DATABASE_URL")

# FastAPI
FASTAPI_ALLOW_ORIGIN = os.environ.get("FASTAPI_ALLOW_ORIGIN")

# JWT
JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY")
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM", "HS256")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = os.environ.get("JWT_ACCESS_TOKEN_EXPIRE_MINUTES", 30)
