name: ci
on:
  push:
    tags:
      - stable

defaults:
  run:
    working-directory: services/backend

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: romainqcz/cenemat:latest
